# Platform, Architecture, and Compiler Detection Module for SRVNet

if(WIN32)
    set(SRVN_OS_WINDOWS 1)

    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(PLATFORM_NAME "Win64")
        set(ARCH_X64 1)
    else()
        set(PLATFORM_NAME "Win32")
        set(ARCH_X86 1)
    endif()
elseif(ANDROID)
    set(SRVN_OS_ANDROID 1)
    set(PLATFORM_NAME "Android")
elseif(APPLE)
    # APPLE must be checked before UNIX — macOS satisfies both
    set(SRVN_OS_MACOS 1)
    set(PLATFORM_NAME "macOS")
elseif(UNIX)
    set(SRVN_OS_LINUX 1)
    set(PLATFORM_NAME "Linux")
else()
    set(PLATFORM_NAME "Generic")
endif()

if(MSVC)
    set(SRVN_COMPILER_MSVC 1)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(SRVN_COMPILER_CLANG_CL 1)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(SRVN_COMPILER_CLANG 1)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(SRVN_COMPILER_GCC 1)
endif()

if(SRVN_COMPILER_MSVC)
    option(SRVN_GENERATE_PDB "True to generate PDB debug symbols, OFF otherwise." ON)
endif()